#!/bin/bash

docker build --build-arg INSIGHT_BRANCH="master" -t $DOCKER_REPO:master .
docker build --build-arg INSIGHT_BRANCH="development" -t $DOCKER_REPO:development .
docker push $DOCKER_REPO:development
