#!/bin/bash

if [[ "$SOURCE_BRANCH" == "master" ]]; then
  docker build --build-arg INSIGHT_TAG="latest" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
fi

if [[ "$SOURCE_BRANCH" == "development" ]]; then
  docker build --build-arg INSIGHT_TAG="development" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
  docker tag $IMAGE_NAME $DOCKER_REPO:development
fi

