#!/bin/bash

if [[ "$SOURCE_BRANCH" == "master" ]]; then
  docker push $DOCKER_REPO:latest
  docker push $DOCKER_REPO:development
fi

#if [[ "$SOURCE_BRANCH" == "development" ]]; then
#  docker build --build-arg INSIGHT_TAG="development" -f $DOCKERFILE_PATH -t $IMAGE_NAME .
#fi

